actions:  
  1:
    action: delete_indices
    description: >-     
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: '^(logstash-|tnapi-|mailws-dev-|validator-|security-).*$'
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 8
  
