version: "3"

services:

  opensearch-node1:
    restart: always
    image: opensearchproject/opensearch:2.9.0
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - plugins.security.ssl.transport.pemkey_filepath=certificates/opensearch-node1/opensearch-node1.key # relative path
      - plugins.security.ssl.transport.pemcert_filepath=certificates/opensearch-node1/opensearch-node1.pem
      - plugins.security.ssl.http.pemkey_filepath=certificates/opensearch-node1/opensearch-node1.key
      - plugins.security.ssl.http.pemcert_filepath=certificates/opensearch-node1/opensearch-node1.pem
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "JAVA_HOME=/usr/share/opensearch/jdk"
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - network.host="0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536  
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-data1:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net 
  
  opensearch-node2:
    restart: always
    image: opensearchproject/opensearch:2.9.0
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - node.name=opensearch-node2
      - cluster.name=opensearch-cluster
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - plugins.security.ssl.transport.pemkey_filepath=certificates/opensearch-node2/opensearch-node2.key # relative path
      - plugins.security.ssl.transport.pemcert_filepath=certificates/opensearch-node2/opensearch-node2.pem
      - plugins.security.ssl.http.pemkey_filepath=certificates/opensearch-node2/opensearch-node2.key
      - plugins.security.ssl.http.pemcert_filepath=certificates/opensearch-node2/opensearch-node2.pem
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - "JAVA_HOME=/usr/share/opensearch/jdk"
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - network.host="0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-data2:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
    networks:
      - opensearch-net  
  
  opensearch-node3:
    restart: always
    image: opensearchproject/opensearch:2.9.0
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - node.name=opensearch-node3
      - cluster.name=opensearch-cluster
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - plugins.security.ssl.transport.pemkey_filepath=certificates/opensearch-node3/opensearch-node3.key # relative path
      - plugins.security.ssl.transport.pemcert_filepath=certificates/opensearch-node3/opensearch-node3.pem
      - plugins.security.ssl.http.pemkey_filepath=certificates/opensearch-node3/opensearch-node3.key
      - plugins.security.ssl.http.pemcert_filepath=certificates/opensearch-node3/opensearch-node3.pem
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "JAVA_HOME=/usr/share/opensearch/jdk"
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - network.host="0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "opensearch-data3:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
    networks:
      - opensearch-net   
  
  kibana:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.9.0
    ports:
      - 5601:5601
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates:ro"
      - "./opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]' # must be a string with no spaces when specified as an environment variable
      DISABLE_INSTALL_DEMO_CONFIG: "true"
  
  os-proxy:
    build: 
        context: ./proxy/
        dockerfile: "Dockerfile"
    container_name: os-proxy
    volumes:
      - ./proxy/config/nginx.os-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - opensearch-net
    stop_grace_period: 10s
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    ports:
      - 9200:9200  
      - 443:443      
    depends_on:
      - opensearch-node1
      - opensearch-node2
      - opensearch-node3
    restart: on-failure

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:      
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5044
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"      
    networks:
      - opensearch-net
    depends_on:
      - os-proxy  
      
  curator:
    build:
      context: ./curator
    container_name: curator
    volumes:
      - ./curator/config:/config
    environment:
      UNIT: days
      UNIT_COUNT: 15
    mem_limit: 256m
    memswap_limit: 0
    restart: on-failure
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    networks:
      - opensearch-net
    depends_on:
      - os-proxy  

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:

networks:
  opensearch-net: